spring:
  profiles:
    active: dev
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ws
    url: jdbc:mysql://localhost:3306/ws_user_center
    #失效时间是1天
  session:
    timeout: 86400
    #配置Swagger的策略
  mvc:
    path match:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)