spring:
  profiles:
    active: dev
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ws
    url: jdbc:mysql://localhost:3306/ws_user_center
    #失效时间是1天
  session:
    timeout: 86400
    #配置Swagger的策略
    store-type: redis
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: 192.168.200.136
    database: 1
    #由于有密码的存在每次进行数据库连接都要设置密码
    password: 'ws'
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

